# domain/interfaces/__init__.py
from domain.interfaces.game_repository_interface import IGameRepository
from domain.interfaces.bot_strategy_interface import IBotStrategy
from domain.interfaces.player_repository_interface import IPlayerRepository